#!/usr/bin/env python
import argparse

import pycnv


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Copy Number Variant detector for diagnostic NGS-pipeline")

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--create', action='store_true', help='Maak nieuwe database')
    group.add_argument('--analyse', action='store_true', help='Voer analyse uit')

    parser.add_argument('-c', '--capture', type=str, required=True, metavar='.',
                        help='Code van de capture als in de versiebeheerlijst')
    parser.add_argument('-n', '--nieuw', type=str, metavar='',
                        help='DoC sample_interval_summary file')
    parser.add_argument('-s', '--serie', type=str, metavar='',
                        help='Serie bijv. Serie110 of SerieDL012')
    parser.add_argument('-o', '--output', type=str, metavar='',
                        help='Output directory. Vervangt config.py')
    parser.add_argument('--sample', type=str, metavar='', help='SampleID')
    parser.add_argument('--addonly', action='store_true',
                        help='DoC aan database toevoegen zonder analyse')

    parser.add_argument('-i', '--ingestuurd', type=str, metavar='',
                        help='TSV File met ingestuurde samples: Serie SampleID Code')
    parser.add_argument('-b', '--bed', type=str, metavar='',
                        help='BED file geannoteerd met GEN')
    parser.add_argument('-g', '--genelist', type=str, metavar='', nargs='*',
                        help='Lijst met gennamen voor rapportage')
    parser.add_argument('-p', '--poscontroles', type=str, metavar='',
                        help='TSV File met positieve controles: Capture Gen SampleID Dup/Del')
    parser.add_argument('--configfile', type=str, metavar='',
                        help='File met locaties voor databases en output')
    args = parser.parse_args()

    if args.create:
        pycnv.create_database(args, configfile=args.configfile)
    elif args.analyse:
        pycnv.analyse(capture=args.capture, serie=args.serie, docfile=args.nieuw,
                      sample=args.sample, outdir=args.output, reportgenes=args.genelist,
                      addonly=args.addonly, configfile=args.configfile)
