#!/usr/bin/env python
import argparse

import pycnv


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Copy Number Variant detector for diagnostic NGS-pipeline")

    parser.add_argument('--create', action='store_true', metavar='',
                        help='Maak nieuwe database')
    parser.add_argument('-c', '--capture', type=str, metavar='.',
                        help='Code van de capture als in de versiebeheerlijst')
    parser.add_argument('-n', '--nieuw', type=str, metavar='',
                        help='DoC sample_interval_summary file')
    parser.add_argument('-s', '--serie', type=str, metavar='',
                        help='Serienummer')
    parser.add_argument('-o', '--output', type=str, metavar='',
                        help='Output directory.')
    parser.add_argument('--sample', type=str, metavar='', help='SampleID')
    parser.add_argument('--addonly', action='store_true',
                        help='Alleen DoC aan db toevoegen')
    parser.add_argument('-i', '--ingestuurd', type=str, metavar='',
                        help='TSV File met ingestuurde samples: Serie SampleID Code')
    parser.add_argument('-b', '--bed', type=str, metavar='',
                        help='BED file geannoteerd met GEN')
    parser.add_argument('-g', '--genelist', type=str, metavar='', nargs='*',
                        help='Lijst met gennamen voor rapportage')
    parser.add_argument('-p', '--poscontroles', type=str, metavar='',
                        help='TSV File met positieve controles: Capture Gen SampleID Dup/Del')

    args = parser.parse_args()

    if args.create:
        pycnv.create_database(args)
    else:
        if not args.capture:
            raise ValueError('Geen capture opgegeven')
        elif not args.serie and not args.sample:
            raise ValueError('Geen serie of sample opgegeven')
        pycnv.analyse(capture=args.capture, serie=args.serie, docfile=args.nieuw,
                      sample=args.sample, outdir=args.output, reportgenes=args.genelist,
                      addonly=args.addonly)
